# Generated by Django 5.0.6 on 2024-06-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project4_App_level', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
