# Generated by Django 5.0.6 on 2024-06-22 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project4_App_level', '0005_userprofile_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project4_App_level.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project4_App_level.userprofile')),
            ],
        ),
    ]
