# Generated by Django 5.0.6 on 2024-06-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project4_App_level', '0006_userstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stocks',
        ),
    ]
